// 정식 추가 콘텐츠: 접촉 공격 카드.
// 베타 카드와 분리해 관리하며 data.js에서 실제 카드 풀에 병합합니다.
export const CONTACT_ATTACK_CARDS = {
  contact_glass_dropper_strike: {
    name: "유리 스포이트 타격",
    englishName: "Glass Dropper Strike",
    cost: 1,
    note: "top",
    attack: 8,
    attackPattern: "contact",
    text: "접촉 피해 8",
  },
  contact_direct_oil_dab: {
    name: "직접 바른 원액",
    englishName: "Direct Oil Dab",
    cost: 1,
    note: "middle",
    attack: 5,
    attackPattern: "contact",
    oil: true,
    absorb: 4,
    text: "접촉 피해 5 · 오일 발동 · 흡수 +4",
  },
  contact_shattered_ampoule: {
    name: "앰플 파쇄",
    englishName: "Shattered Ampoule",
    cost: 1,
    note: "top",
    attack: 6,
    attackPattern: "contact",
    applyEnemy: { vulnerable: 1 },
    text: "접촉 피해 6 · 취약 +1",
  },
  contact_beveled_scent_strip: {
    name: "날카로운 시향지",
    englishName: "Beveled Scent Strip",
    cost: 0,
    note: "top",
    attack: 3,
    attackPattern: "contact",
    applyEnemy: { bleed: { stacks: 2, turns: 2 } },
    text: "접촉 피해 3 · 출혈 +2 (2턴)",
  },
  contact_woody_pestle_smash: {
    name: "우디 스틱 강타",
    englishName: "Woody Pestle Smash",
    cost: 2,
    note: "base",
    attack: 14,
    attackPattern: "contact",
    applyEnemy: { weak: 1 },
    text: "접촉 피해 14 · 약화 +1",
  },
  contact_coating_slam: {
    name: "코팅 밀착타",
    englishName: "Coating Slam",
    cost: 1,
    note: "base",
    attack: 5,
    attackPattern: "contact",
    shieldScaling: 0.25,
    text: "접촉 피해 5 + 현재 방어막 25% 추가 피해 (방어막 소모 없음)",
  },
  contact_fierce_rub: {
    name: "맹렬한 문지름",
    englishName: "Fierce Rub",
    cost: 1,
    note: "middle",
    attack: 3,
    hits: 3,
    attackPattern: "contact",
    text: "접촉 피해 3 × 3회",
  },
  contact_grind_refine: {
    name: "분쇄 정제",
    englishName: "Grind & Refine",
    cost: 2,
    note: "middle",
    attack: 11,
    attackPattern: "contact",
    refundOnBreak: 1,
    text: "접촉 피해 11 · 방어막 파괴 시 AP +1",
  },
  contact_censer_shove: {
    name: "향로 밀치기",
    englishName: "Censer Shove",
    cost: 1,
    note: "base",
    attack: 7,
    attackPattern: "contact",
    applyEnemy: { burning: { stacks: 3, turns: 2 } },
    text: "접촉 피해 7 · 연소 +3 (2턴)",
  },
  contact_perfumers_touch: {
    name: "조향사의 일격",
    englishName: "Perfumer's Touch",
    cost: 2,
    note: "top",
    attack: 12,
    attackPattern: "contact",
    comboContactBonus: 6,
    text: "접촉 피해 12 · 이번 턴 선행 접촉 카드가 있으면 피해 18",
  },
};
