import assert from 'node:assert/strict';
import { judgeDrop, resultRank } from '../src/rules.js';
assert.equal(resultRank(0).name,'향기 새싹');
assert.equal(resultRank(1999).name,'향기 새싹');
assert.equal(resultRank(2000).name,'공간 조향사');
assert.equal(resultRank(3999).name,'공간 조향사');
assert.equal(resultRank(4000).name,'결이든 마스터');
import { resultLink, readResult } from '../src/share.js';
import { visitorCount, scentCount, dialogueTemplates, createAtmosphere } from '../src/atmosphere.js';
import { poses, expressions, makeVisitor } from '../src/visitors.js';
assert.equal(poses.length,12);
assert.equal(expressions.length,8);
for(const pose of poses)for(const arm of pose.arms)assert.ok(arm[3]>=arm[1], 'Elbows must stay below shoulders');
for(let seed=0;seed<120;seed++){
  const group=Array.from({length:10},(_,i)=>makeVisitor(i,seed));
  assert.equal(new Set(group.map(g=>g.pose.name)).size,10);
  assert.equal(new Set(group.map(g=>g.expression)).size,8);
}
assert.equal(new Set(dialogueTemplates).size,20);
for (const [combo,count] of [[0,0],[4,0],[5,1],[9,1],[10,2],[49,9],[50,10],[500,10]]) assert.equal(scentCount(combo),count);
for (const [combo, count] of [[0,0],[9,0],[10,1],[19,1],[20,2],[30,3],[40,4],[50,5],[60,6],[90,9],[100,10],[200,10]]) assert.equal(visitorCount(combo),count);
const atmosphere = createAtmosphere();
const labels = [];
const drawing = new Proxy({}, {get:(_,name)=>name==='fillText'?(text)=>labels.push(text):()=>{},set:()=>true});
atmosphere.update(1,50,false); atmosphere.draw(drawing,1,false);
assert.equal(labels.length,5);
assert.equal(new Set(labels).size,5);
assert.ok(labels.every(text=>dialogueTemplates.includes(text)));
const previousLabels=[...labels];
labels.length=0; atmosphere.update(7,50,false); atmosphere.draw(drawing,8,false);
assert.ok(labels.every((text,i)=>text!==previousLabels[i]));
assert.equal(new Set(labels).size,5);
labels.length=0; atmosphere.update(1,0,false); atmosphere.draw(drawing,2,false);
assert.equal(labels.length,0);
atmosphere.update(1,100,false); atmosphere.draw(drawing,3,false);
assert.equal(labels.length,10);
assert.equal(new Set(labels).size,10);
labels.length=0; atmosphere.update(1,200,false); atmosphere.draw(drawing,4,false);
assert.equal(labels.length,10);
const record = {stone:'pink',score:1250,combo:8,hits:10};
const link = resultLink('https://example.github.io/my-game/index.html?old=1#old', record);
assert.equal(new URL(link).pathname, '/my-game/index.html');
assert.deepEqual(readResult(link), record);
assert.equal(readResult('https://example.github.io/?result=1&stone=bad'), null);
assert.equal(readResult(link.replace('score=1250', 'score=-1')), null);
assert.equal(readResult(link.replace('combo=8', 'combo=100')), null);
assert.equal(judgeDrop(240,0).points,100);
assert.equal(judgeDrop(240,0).combo,2);
assert.equal(judgeDrop(240,0).timeDelta,2);
assert.equal(judgeDrop(307,0).timeDelta,-1);
assert.equal(judgeDrop(260,0).timeDelta,0);
const longRecord = {stone:'pink',score:120000,combo:1500,hits:800};
assert.deepEqual(readResult(resultLink('https://example.github.io/game/',longRecord)),longRecord);
assert.equal(judgeDrop(240,9).combo,11);
assert.equal(judgeDrop(260,9).combo,10);
assert.equal(visitorCount(judgeDrop(240,9).combo),1);
const perfectRecord = {stone:'green',score:900,combo:12,hits:6};
assert.deepEqual(readResult(resultLink('https://example.github.io/game/', perfectRecord)), perfectRecord);
assert.equal(readResult(resultLink('https://example.github.io/game/', {...perfectRecord,combo:13})),null);
assert.equal(judgeDrop(258,2).points,100);
assert.equal(judgeDrop(259,0).points,80);
assert.equal(judgeDrop(306,0).points,25);
for (const [distance, grade, points] of [[0,'PERFECT',100],[8.5,'PERFECT',100],[8.51,'EXCELLENT',80],[10,'EXCELLENT',80],[24,'EXCELLENT',80],[24.01,'GOOD',50],[44,'GOOD',50],[44.01,'NOT BAD',25],[66,'NOT BAD',25],[66.01,'BAD',0],[175,'BAD',0]]) {
  for (const sign of [-1, 1]) {
    const result = judgeDrop(240 + sign * distance, 0);
    assert.equal(result.grade, grade);
    assert.equal(result.points, points);
  }
}
assert.equal(judgeDrop(307,5).combo,0);
assert.equal(judgeDrop(240,99).points,200);
// Simulate the complete game lifecycle with a minimal DOM and canvas adapter.
const elements = new Map();
function element(id){if(!elements.has(id))elements.set(id,{textContent:'',style:{},hidden:false,tagName:'BODY',events:{},addEventListener(name,fn){this.events[name]=fn;},setAttribute(){},prepend(){},classList:{toggle(){}}});return elements.get(id);}
const buttons=['pink','green','volcanic'].map(type=>Object.assign(element(type),{dataset:{stone:type}}));
const context=new Proxy({}, {get:(_,name)=>()=>{},set:()=>true});
element('game').getContext=()=>context;
const documentEvents = {};
globalThis.document={getElementById:element,createElement:()=>element('image'),querySelector:element,querySelectorAll:()=>buttons,activeElement:{tagName:'BODY'},addEventListener(name,fn){documentEvents[name]=fn;}};
globalThis.localStorage={getItem:()=>null,setItem(){}};
globalThis.window={location:{href:'https://example.github.io/my-game/',hostname:'example.github.io'},history:{replaceState(){}}};
let nextFrame;
globalThis.requestAnimationFrame=fn=>{nextFrame=fn;};
await import('../src/main.js');
element('action').events.click();
assert.ok(buttons.every(b=>b.disabled));
element('action').events.click();
let time=100;
for(let i=0;i<30;i++)nextFrame(time+=16);
assert.equal(element('score').textContent,100);
assert.equal(element('feedback').textContent,'PERFECT +100 · +2초');
assert.equal(element('time').textContent,32);
element('pause').events.click();
const pausedTime=element('time').textContent;
for(let i=0;i<100;i++)nextFrame(time+=16);
assert.equal(element('time').textContent,pausedTime);
element('pause').events.click();
for(let i=0;i<2000;i++)nextFrame(time+=16);
assert.equal(element('result').hidden,false);
assert.equal(element('time').textContent,0);
assert.ok(buttons.every(b=>!b.disabled));
const space = { code:'Space', repeat:false, preventDefault(){} };
documentEvents.keydown(space);
assert.equal(element('result').hidden,false, 'Space on page must not restart');
document.activeElement=element('action');
document.activeElement.tagName='BUTTON';
documentEvents.keydown(space);
documentEvents.keyup(space);
assert.equal(element('result').hidden,false, 'Space on focused action must not restart');
element('action').events.click();
assert.equal(element('result').hidden,true);
assert.equal(element('score').textContent,0);
assert.equal(element('time').textContent,30);
documentEvents.keydown(space);
for(let i=0;i<30;i++)nextFrame(time+=16);
assert.equal(element('score').textContent,100, 'Space on focused action drops during play');
console.log('PASS: scoring boundaries, combo cap, drop, pause/resume, 30-second finish, restart.');
window.location.href=link;
await import('../src/main.js?shared-result-test');
assert.equal(element('result').hidden,false);
assert.equal(element('total').textContent,'1250점');
assert.equal(element('action').textContent,'나도 도전하기 →');
assert.equal(element('best').textContent,0);
element('action').events.click();
assert.equal(element('score').textContent,0);
console.log('PASS: GitHub Pages subpath, result link roundtrip, invalid links, friend result, fresh challenge.');
