import { levels, buildDeck, challengeConfig, clearScore } from './data.js';
import { shareChallengeRecord, shareChallengeKakao, shareChallengeLink } from './share.js';
const $=s=>document.querySelector(s),board=$('#board');
let levelIndex=0,challenge=false,challengeLevel=6,challengeScore=0,lives=3,phase='ready',opened=[],matched=0,deadline=0,frameRequest=0,roundToken=0,sound=false,audio;
let best=loadBest();
function loadBest(){try{const v=JSON.parse(localStorage.getItem('gyeolideun-memory-best'));return{score:Math.max(0,+v?.score||0),level:Math.max(5,+v?.level||5)}}catch{return{score:0,level:5}}}
function saveBest(){best.score=Math.max(best.score,challengeScore);best.level=Math.max(best.level,challengeLevel);try{localStorage.setItem('gyeolideun-memory-best',JSON.stringify(best))}catch{}}
const config=()=>challenge?challengeConfig(challengeLevel):levels[levelIndex];
function tone(f){if(!sound)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.18)}catch{}}
function updateStats(remaining=config().seconds){const c=config();$('#level').textContent=challenge?`${challengeLevel} CHALLENGE`:`${c.level} / ${levels.length}`;$('#time').textContent=challenge?'∞':String(Math.max(0,Math.ceil(remaining)));$('#matches').textContent=`${matched} / ${c.pairs}`;$('#timer-bar').style.width=challenge?'100%':`${Math.max(0,remaining/c.seconds)*100}%`;$('#lives-stat').hidden=!challenge;$('#lives').textContent=`${'♥ '.repeat(lives).trim()}${lives<3?` ${'♡ '.repeat(3-lives).trim()}`:''}`;$('#challenge-score').textContent=challengeScore.toLocaleString('ko-KR')}
function cardElement(card){const b=document.createElement('button');b.type='button';b.className='memory-card';b.dataset.motif=card.id;b.dataset.cardId=card.cardId;b.style.setProperty('--card-accent',card.accent);b.setAttribute('aria-label','뒤집히지 않은 향기 카드');b.innerHTML='<span class="memory-card-inner"><span class="card-face card-back"></span><span class="card-face card-front"><b class="card-code"></b><i class="card-symbol"></i><span class="card-label"></span></span></span>';const f=b.querySelector('.card-front');f.style.backgroundImage=`url('${card.image}')`;f.style.backgroundPosition=card.position;f.style.backgroundSize=card.size;f.querySelector('.card-code').textContent=card.code;f.querySelector('.card-symbol').textContent=card.symbol;f.querySelector('.card-label').textContent=card.label;return b}
function prepareLevel(){cancelAnimationFrame(frameRequest);roundToken++;phase='ready';opened=[];matched=0;const c=config();board.style.setProperty('--columns',c.pairs===3?3:4);board.replaceChildren(...buildDeck(c.pairs).map(cardElement));if(challenge)board.querySelectorAll('.memory-card').forEach(x=>x.classList.add('is-open'));$('#cover-kicker').textContent=challenge?`CHALLENGE · LEVEL ${challengeLevel}`:`LEVEL ${c.level}`;$('#cover-title').textContent=challenge?'목숨 3개로 기록에 도전하세요':'향기 조각을 기억해보세요';const preview=(c.preview/1000).toFixed(2).replace(/0+$/,'').replace(/\.$/,'');$('#cover-copy').innerHTML=challenge?`카드를 충분히 외운 뒤 원하는 순간에 시작하세요. 시작하면 카드가 모두 뒤집혀요.<br>${c.hideLabel?'그림만 보고':c.hideSymbol?'번호와 기호 없이':c.hideCode?'번호 없이':'그림과 표시를 함께 보며'} 짝을 찾아주세요.`:`처음 ${preview}초 동안 카드가 공개돼요.<br>같은 그림 ${c.pairs}쌍을 찾아주세요.`;$('#start').textContent=challenge?`챌린지 레벨 ${challengeLevel} 시작`:`레벨 ${c.level} 시작하기`;const shell=$('.game-shell');shell.classList.toggle('challenge-mode',challenge);shell.classList.toggle('challenge-ready',challenge);shell.classList.toggle('hide-card-code',challenge&&c.hideCode);shell.classList.toggle('hide-card-symbol',challenge&&c.hideSymbol);shell.classList.toggle('hide-card-label',challenge&&c.hideLabel);$('#level-result').hidden=true;$('#cover').hidden=false;$('#share-status').textContent='';updateStats()}
function showRecords(){saveBest();$('#record-box').hidden=false;$('#record-share-actions').hidden=false;$('#best-score').textContent=best.score.toLocaleString('ko-KR');$('#best-level').textContent=String(best.level)}
function finishLevel(cleared,reason='time'){cancelAnimationFrame(frameRequest);phase='result';const c=config();$('#level-result').hidden=false;$('#record-box').hidden=!challenge;$('#record-share').hidden=!challenge;if(challenge){if(cleared){const remaining=0,lifeBonus=lives*300,gained=clearScore(challengeLevel,remaining,lives);challengeScore+=gained;lives=3;tone(880);saveBest();$('#result-kicker').textContent='CHALLENGE CLEAR';$('#result-title').textContent=`레벨 ${challengeLevel}을 돌파했어요!`;$('#result-copy').textContent=`+${gained.toLocaleString('ko-KR')}점 (생명 보너스 +${lifeBonus.toLocaleString('ko-KR')}) · 누적 ${challengeScore.toLocaleString('ko-KR')}점 · 목숨이 3개로 회복됐어요.`;$('#next').textContent=`레벨 ${challengeLevel+1} 계속하기`;$('#next').dataset.action='challenge-next'}else{saveBest();$('#result-kicker').textContent='CHALLENGE OVER';$('#result-title').textContent=reason==='lives'?'목숨을 모두 사용했어요':'시간이 모두 지났어요';$('#result-copy').textContent=`이번 기록 ${challengeScore.toLocaleString('ko-KR')}점 · 도달 레벨 ${challengeLevel}`;$('#next').textContent='챌린지 레벨 6부터 다시하기';$('#next').dataset.action='challenge-restart'}updateStats(0);showRecords();return}if(cleared){const remaining=Math.max(0,(deadline-performance.now())/1000),gained=clearScore(c.level,remaining);challengeScore+=gained;tone(880);$('#result-kicker').textContent=c.level===levels.length?'NORMAL CLEAR':'LEVEL CLEAR';$('#result-title').textContent=c.level===levels.length?'기본 단계를 모두 완성했어요!':'모든 향기 조각을 찾았어요!';$('#result-copy').textContent=c.level===levels.length?`+${gained.toLocaleString('ko-KR')}점 · 누적 ${challengeScore.toLocaleString('ko-KR')}점 · 무한 챌린지가 열렸어요.`:`+${gained.toLocaleString('ko-KR')}점 · 누적 ${challengeScore.toLocaleString('ko-KR')}점`;$('#next').textContent=c.level===levels.length?'챌린지 모드 시작하기':`레벨 ${c.level+1} 도전하기`;$('#next').dataset.action=c.level===levels.length?'challenge-start':'normal-next';updateStats(remaining)}else{$('#result-kicker').textContent='TIME OVER';$('#result-title').textContent='향기 조각이 아직 남아 있어요';$('#result-copy').textContent=`${c.pairs-matched}쌍만 더 찾으면 돼요. 카드를 다시 기억해볼까요?`;$('#next').textContent='같은 레벨 다시하기';$('#next').dataset.action='normal-retry'}}
function timerFrame(now){if(phase!=='playing')return;const r=(deadline-now)/1000;updateStats(r);if(r<=0)return finishLevel(false,'time');frameRequest=requestAnimationFrame(timerFrame)}
function beginLevel(){const token=roundToken,c=config();$('#cover').hidden=true;if(challenge){board.querySelectorAll('.memory-card').forEach(x=>x.classList.remove('is-open'));$('.game-shell').classList.remove('challenge-ready');phase='playing';deadline=Infinity;updateStats();return}phase='preview';board.querySelectorAll('.memory-card').forEach(x=>x.classList.add('is-open'));setTimeout(()=>{if(token!==roundToken)return;board.querySelectorAll('.memory-card').forEach(x=>x.classList.remove('is-open'));phase='playing';deadline=performance.now()+c.seconds*1000;frameRequest=requestAnimationFrame(timerFrame)},c.preview)}
board.addEventListener('click',e=>{const card=e.target.closest('.memory-card');if(!card||phase!=='playing'||card.classList.contains('is-open')||card.classList.contains('is-matched')||opened.length===2)return;card.classList.add('is-open');card.setAttribute('aria-label',card.querySelector('.card-label').textContent);opened.push(card);tone(520);if(opened.length<2)return;const[first,second]=opened;if(first.dataset.motif===second.dataset.motif){first.classList.add('is-matched');second.classList.add('is-matched');opened=[];matched++;updateStats((deadline-performance.now())/1000);tone(740);if(matched===config().pairs)finishLevel(true);return}if(challenge){lives--;updateStats((deadline-performance.now())/1000);tone(220)}const token=roundToken;setTimeout(()=>{if(token!==roundToken)return;first.classList.remove('is-open');second.classList.remove('is-open');first.setAttribute('aria-label','뒤집히지 않은 향기 카드');second.setAttribute('aria-label','뒤집히지 않은 향기 카드');opened=[];if(challenge&&lives<=0)finishLevel(false,'lives')},config().mismatchDelay||650)});
$('#start').addEventListener('click',beginLevel);$('#next').addEventListener('click',()=>{const a=$('#next').dataset.action;if(a==='challenge-start'){challenge=true;challengeLevel=6;lives=3}else if(a==='challenge-restart'){challenge=true;challengeLevel=6;challengeScore=0;lives=3}else if(a==='challenge-next'){challengeLevel++;lives=3}else if(a==='normal-next')levelIndex++;prepareLevel()});$('#sound').addEventListener('click',()=>{sound=!sound;$('#sound').textContent=sound?'소리 켜짐':'소리 꺼짐';$('#sound').setAttribute('aria-pressed',String(sound));tone(660)});$('#record-share').addEventListener('click',async()=>{try{$('#share-status').textContent=await shareChallengeRecord(best)}catch(e){$('#share-status').textContent=e.name==='AbortError'?'공유를 취소했어요.':'이미지를 공유하거나 저장하지 못했어요.'}});prepareLevel();
$('#kakao-record-share').addEventListener('click',async()=>{try{await shareChallengeKakao(best);$('#share-status').textContent='카카오톡에서 공유할 대상을 선택해 주세요.'}catch{$('#share-status').textContent='카카오톡 공유를 열지 못했어요. 배포 주소와 카카오 설정을 확인해 주세요.'}});
$('#link-record-share').addEventListener('click',async()=>{try{$('#share-status').textContent=await shareChallengeLink(best)}catch(e){$('#share-status').textContent=e.name==='AbortError'?'공유를 취소했어요.':'링크를 공유하지 못했어요.'}});
