const toFile=(canvas,name)=>new Promise(resolve=>canvas.toBlob(blob=>resolve(new File([blob],name,{type:'image/png'})),'image/png'));
const PUBLIC_ROOT='https://minsung0732.github.io/gid/';
const PUBLIC_PAGE=`${PUBLIC_ROOT}games/memory/`;
const KAKAO_KEY='6716e83b61647bd3bd1977dd655aa93b';
let kakaoPromise;
function loadKakao(){if(window.Kakao)return Promise.resolve(window.Kakao);kakaoPromise||=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://t1.kakaocdn.net/kakao_js_sdk/2.8.3/kakao.min.js';script.integrity='sha384-oroumrnFVE0xtgqyDZJARgERibXg2C28380uaUZz2kHDS5CR7tu20eGiOU6GkTpy';script.crossOrigin='anonymous';script.onload=()=>resolve(window.Kakao);script.onerror=()=>reject(new Error('Kakao SDK unavailable'));document.head.append(script)});return kakaoPromise}
export async function shareChallengeKakao(record){const kakao=await loadKakao();if(!kakao.isInitialized())kakao.init(KAKAO_KEY);kakao.Share.sendDefault({objectType:'feed',content:{title:'향기의 기억 챌린지',description:`최고 ${record.score.toLocaleString('ko-KR')}점 · LEVEL ${record.level}`,imageUrl:`${PUBLIC_ROOT}public/assets/memory/blossom-bouquet.png`,link:{mobileWebUrl:PUBLIC_PAGE,webUrl:PUBLIC_PAGE}},buttons:[{title:'나도 기억력 도전하기',link:{mobileWebUrl:PUBLIC_PAGE,webUrl:PUBLIC_PAGE}}]})}
export async function createChallengeCard(record){const c=document.createElement('canvas');c.width=c.height=1080;const x=c.getContext('2d');x.fillStyle='#FAFAF5';x.fillRect(0,0,1080,1080);x.fillStyle='#235347';x.fillRect(0,0,1080,22);x.fillStyle='#235347';x.font='700 38px sans-serif';x.fillText('GYEOLIDEUN · SCENT MEMORY',70,115);x.fillStyle='#333331';x.font='700 64px serif';x.fillText('향기의 기억 챌린지',70,230);x.fillStyle='#F3E9DC';x.fillRect(70,310,940,430);x.fillStyle='#235347';x.font='28px sans-serif';x.fillText('최고 점수',130,410);x.font='700 92px sans-serif';x.fillText(`${record.score.toLocaleString('ko-KR')}점`,130,530);x.fillStyle='#BD4860';x.font='28px sans-serif';x.fillText('최고 도달 레벨',130,625);x.font='700 64px sans-serif';x.fillText(`LEVEL ${record.level}`,130,700);x.fillStyle='#333331';x.font='30px sans-serif';x.fillText('목숨 3개로 당신의 기억력에 도전해보세요.',70,855);x.fillStyle='#235347';x.font='24px sans-serif';x.fillText('향기는 사라져도 좋은 기억은 오래 머물러요.',70,970);return toFile(c,'gyeolideun-memory-challenge.png')}
export async function shareChallengeRecord(record){const file=await createChallengeCard(record),text=`결이든 향기의 기억 챌린지\n최고 ${record.score.toLocaleString('ko-KR')}점 · LEVEL ${record.level}`;if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'향기의 기억 챌린지',text});return'공유할 앱을 선택해 주세요.'}const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return'최고 기록 이미지를 저장했어요. 원하는 앱에서 선택해 주세요.'}
